DROP TABLE HOBBIES IF exists;
DROP table CONTACTS if exists;



CREATE TABLE CONTACTS
(ID integer NOT NULL PRIMARY KEY,
FNAME CHAR(50),
LNAME CHAR(50));

CREATE TABLE HOBBIES
(ID integer NOT NULL PRIMARY KEY,
HOBBY CHAR(50));

